version: '3.3'
services:
  api:
    build: .
    image: final-project-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    networks:
      - finalprojectcs493team14_default

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - finalprojectcs493team14_mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - finalprojectcs493team14_default

networks:
  finalprojectcs493team14_default:
    driver: bridge

volumes:
  finalprojectcs493team14_mongo-data: